version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    depends_on:
      - backend
      - database
    environment:
      - BACKEND_URL=http://localhost:8080

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    depends_on:
      - database
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  database:
    image: mariadb:latest
    command: --verbose
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: mydatabase
    networks:
      - mynetwork
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 10s

networks:
  mynetwork:
    driver: bridge

volumes:
  mariadb_data:
