# Change with the configuration that corresponds

version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - mynetwork

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    depends_on:
      - database

  database:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: mydatabase
    networks:
      - mynetwork
    volumes:
      - mariadb_data:/var/lib/mysql 
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  mynetwork:
    driver: bridge

volumes:
  mariadb_data:
