version: '3'

services:
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "80:80"
  #   networks:
  #     - mynetwork

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://database:3306/mydatabase
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mypass

  database:
    image: mariadb:latest
    command: --verbose
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: mydatabase
    networks:
      - mynetwork
    ports:
      - 3306:3306
    options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=30s --health-retries=3
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  mynetwork:
    driver: bridge

volumes:
  mariadb_data:
