version: '3'

services:
  frontend:
    build: ./frontend/deskshare
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8080

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    depends_on:
      - database

  database:
    image: mariadb:latest
    command: --verbose
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: mydatabase
    networks:
      - mynetwork
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql

networks:
  mynetwork:
    driver: bridge

volumes:
  mariadb_data:
