version: '3'

services:
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "80:80"
  #   networks:
  #     - mynetwork

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    depends_on:
      - database

  database:
    image: mariadb:latest
    command: --verbose
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: mydatabase
    networks:
      - mynetwork
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql

networks:
  mynetwork:
    driver: bridge

volumes:
  mariadb_data:
