spring:
  datasource:
    url: jdbc:mariadb://database:3306/mydatabase
    password: mypass
    driver-class-name: com.mariadb.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
