name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      # - name: Install frontend dependencies
      #   working-directory: frontend
      #   run: |
      #     npm install

      # - name: Build frontend
      #   working-directory: frontend
      #   run: |
      #     npm run build

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build and test backend with Maven
        working-directory: backend
        run: mvn clean install

      - name: Build and run Docker images
        run: |
          docker-compose build
          docker-compose up -d

      - name: Print Docker Compose logs
        run: docker-compose logs

      - name: Run tests against deployed application
        run: |

      - name: Test Database Initialization
        run: |
          # Assuming your init.sql is in the database folder
          docker run --rm \
            -e MYSQL_ROOT_PASSWORD=mypass \
            -e MYSQL_DATABASE=mydatabase \
            -v $(pwd)/database:/docker-entrypoint-initdb.d \
            mariadb:latest

      - name: Connect to MariaDB container
        run: docker exec -it database-container sh

      - name: Cleanup Docker Compose
        run: |
          docker-compose down